import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "Create Next App", // this is basic title
  // advance
  title: {
    default: "NextJS Playground",
    template: "%s | NextJS Playground",
    absolute: "", // it can be added in page level routes, it completely overrides root layout title
  },

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header
          style={{
            background: "grey",
            color: "white",
            textAlign: "center",
            padding: 10,
          }}
        >
          <h1>Welcome to NextJS Playground.</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
